apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: evergreens.evergreen-ils.org
spec:
  group: evergreen-ils.org
  names:
    kind: evergreen
    listKind: evergreenList
    plural: evergreens
    singular: evergreen
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties: {}
            type: object
        type: object
    served: true
    storage: true