apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: evergreens.evergreen-ils.org
spec:
  group: evergreen-ils.org
  names:
    kind: evergreen
    listKind: evergreenList
    plural: evergreens
    singular: evergreen
  scope: Namespaced
  versions:
  - name: v1
    schema:
      openAPIV3Schema:
        properties:
          spec:
            properties:
              images:
                properties:
                  ejabberd:
                    properties:
                      isManaged:
                        type: boolean
                      repository:
                        type: string
                      tag:
                        type: string
                      pullPolicy:
                        type: string
                      serviceName:
                        type: string
                    type: object
                  memcached:
                    properties:
                      isManaged:
                        type: boolean
                      repository:
                        type: string
                      tag:
                        type: string
                      pullPolicy:
                        type: string
                      serviceName:
                        type: string
                    type: object
                type: object
              database:
                properties:
                  secretRef:
                    type: string
                  passwordKey:
                    type: string
                type: object
              services:
                items:
                  properties:
                    name:
                      type: string
                  type: object
                type: array
            type: object
        type: object
    served: true
    storage: true