include:
#  - opensrf-services-compose.yml
  - single-opensrf-services-compose.yml

services:
  db:
    container_name: db
    env_file: .env
    ports:
      - 5432:5432
    build:
      dockerfile: /Dockerfile
      context: ../build
      target: postgres-ils
    networks:
      - private
    restart: unless-stopped
  db-init:
    container_name: db-init
    env_file: .env
    build:
      dockerfile: Dockerfile
      context: ../build
      target: db-init
    networks:
      - private
    depends_on:
      db:
          condition: service_started
  pgadmin:
    container_name: pg_admin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@mycomp.com
      PGADMIN_DEFAULT_PASSWORD: secret
      PGADMIN_CONFIG_SERVER_MODE: 'False'
      PGADMIN_LISTEN_PORT: 80
    ports:
      - 5050:80
    networks:
      - private
      - public
    depends_on:
      - db
  router:
    container_name: router
    hostname: opensrf.router
    restart: unless-stopped
    build:
      dockerfile: Dockerfile
      context: ../build
      target: router
    depends_on:
      ejabberd:
        condition: service_healthy
    networks:
      - private
      - public
  opensrf-websocket:
    container_name: opensrf-websocket
    build:
      dockerfile: Dockerfile
      context: ../build
      target: opensrf-websocket
    depends_on:
      router:
        condition: service_healthy
    restart: unless-stopped
    ports:
      - 7682:7682
    networks:
      - private
      - public
  evergreen:
    hostname: evergreen
    container_name: evergreen
    ports:
      - 80:80
    build:
      dockerfile: Dockerfile
      context: ../build
      target: evergreen
    env_file: .env
    environment:
      EVERGREEN_NO_SSL: true
    depends_on:
      db-init:
        condition: service_completed_successfully
      opensrf:
        condition: service_started
      # opensrf-settings:
      #   condition: service_started
      # open-ils-cstore:
      #   condition: service_started
      # open-ils-actor:
      #   condition: service_started
    restart: unless-stopped
    networks:
      - private
      - public
  memcached:
    container_name: memcached
    image: memcached
    command:
      - --conn-limit=1024
      - --memory-limit=64
      - --threads=4
    networks:
      - private
  ejabberd:
    container_name: ejabberd
    image: ejabberd/ecs
    restart: unless-stopped
    environment:
      CTL_ON_CREATE: register opensrf public-ejabberd password ;
                      register opensrf private-ejabberd password ;
                      register router public-ejabberd password ;
                      register router private-ejabberd password ;
                      status
    networks:
      private:
        aliases:
          - private-ejabberd
      public:
        aliases:
          - public-ejabberd
    healthcheck:
      test: netstat -nl | grep -q 5222
      start_period: 5s
      interval: 5s
      timeout: 5s
      retries: 120
    ports:
      - 5222:5222
      - 5269:5269
      - 5280:5280
      - 5443:5443
    volumes:
    - type: bind
      source: ../config/ejabberd/ejabberd.yml
      target: /home/ejabberd/conf/ejabberd.yml

networks:
  private:
  public: