services:
  opensrf:
    container_name: opensrf
    build:
      dockerfile: Dockerfile
      context: ../build
      target: osrf-service
    restart: unless-stopped
    env_file: .env
    depends_on:
      router:
        condition: service_healthy
      db-init:
        condition: service_completed_successfully
    networks:
      - private
  