apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "evergreen.fullname" . }}-websocket
  labels:
    {{- include "evergreen.labels" . | nindent 4 }}
    app.kubernetes.io/component: websocket
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "evergreen.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: websocket
  template:
    metadata:
      labels:
        {{- include "evergreen.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: websocket
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        {{- include "evergreen.waitForEjabberd" . | nindent 8 }}
      containers:
        - name: websocket
          image: {{ include "evergreen.image" (dict "global" .Values.global "image" .Values.websocket.image) }}
          imagePullPolicy: {{ .Values.websocket.image.pullPolicy }}
          ports:
            - containerPort: 7682
              protocol: TCP
          readinessProbe:
            tcpSocket:
              port: 7682
            initialDelaySeconds: 10
            periodSeconds: 10
          {{- with .Values.websocket.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
