apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "evergreen.fullname" . }}-web
  labels:
    {{- include "evergreen.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
spec:
  replicas: 1
  selector:
    matchLabels:
      {{- include "evergreen.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: web
  template:
    metadata:
      labels:
        {{- include "evergreen.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: web
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      initContainers:
        {{- include "evergreen.waitForEjabberd" . | nindent 8 }}
        - name: wait-for-opensrf
          image: busybox:1.36
          command: ['sh', '-c', 'sleep 30']
      containers:
        - name: web
          image: {{ include "evergreen.image" (dict "global" .Values.global "image" .Values.web.image) }}
          imagePullPolicy: {{ .Values.web.image.pullPolicy }}
          env:
            {{- include "evergreen.dbEnv" . | nindent 12 }}
            - name: EVERGREEN_NO_SSL
              value: "true"
          ports:
            - containerPort: 80
              protocol: TCP
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 30
            periodSeconds: 10
          {{- with .Values.web.resources }}
          resources:
            {{- toYaml . | nindent 12 }}
          {{- end }}
