apiVersion: v1
kind: Secret
metadata:
  name: {{ include "evergreen.fullname" . }}-db
  labels:
    {{- include "evergreen.labels" . | nindent 4 }}
type: Opaque
stringData:
  username: {{ .Values.auth.postgresUser | quote }}
  password: {{ .Values.auth.postgresPassword | quote }}
  database: {{ .Values.auth.postgresDatabase | quote }}
  admin-username: {{ .Values.auth.postgresAdminUser | quote }}
  admin-password: {{ .Values.auth.postgresAdminPassword | quote }}
