apiVersion: v1
kind: Service
metadata:
  name: {{ include "evergreen.fullname" . }}-websocket
  labels:
    {{- include "evergreen.labels" . | nindent 4 }}
    app.kubernetes.io/component: websocket
spec:
  type: {{ .Values.websocket.service.type }}
  ports:
    - port: {{ .Values.websocket.service.port }}
      targetPort: 7682
      protocol: TCP
  selector:
    {{- include "evergreen.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: websocket
