apiVersion: v1
kind: Service
metadata:
  name: memcached
  labels:
    {{- include "evergreen.labels" . | nindent 4 }}
    app.kubernetes.io/component: memcached
spec:
  type: ClusterIP
  ports:
    - port: 11211
      targetPort: 11211
      protocol: TCP
  selector:
    {{- include "evergreen.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: memcached
