apiVersion: v1
kind: Service
metadata:
  name: {{ include "evergreen.fullname" . }}-db
  labels:
    {{- include "evergreen.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    {{- include "evergreen.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: database
