apiVersion: v1
kind: Service
metadata:
  name: private-ejabberd
  labels:
    {{- include "evergreen.labels" . | nindent 4 }}
    app.kubernetes.io/component: ejabberd
spec:
  type: ClusterIP
  ports:
    - port: 5222
      targetPort: 5222
      protocol: TCP
      name: c2s
    - port: 5269
      targetPort: 5269
      protocol: TCP
      name: s2s
    - port: 5280
      targetPort: 5280
      protocol: TCP
      name: http
    - port: 5443
      targetPort: 5443
      protocol: TCP
      name: https
  selector:
    {{- include "evergreen.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ejabberd
---
apiVersion: v1
kind: Service
metadata:
  name: public-ejabberd
  labels:
    {{- include "evergreen.labels" . | nindent 4 }}
    app.kubernetes.io/component: ejabberd
spec:
  type: ClusterIP
  ports:
    - port: 5222
      targetPort: 5222
      protocol: TCP
      name: c2s
    - port: 5269
      targetPort: 5269
      protocol: TCP
      name: s2s
    - port: 5280
      targetPort: 5280
      protocol: TCP
      name: http
    - port: 5443
      targetPort: 5443
      protocol: TCP
      name: https
  selector:
    {{- include "evergreen.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: ejabberd
